project:
  type: book
  output-dir: docs
book:
  title: "Research Design and Analysis: A Computational Model-Based Approach"
  author: "William M. Murrah, III"
  chapters:
    - index.qmd
    - intro.qmd
    - introR.qmd
    - understandingData.qmd
    - dgp.qmd
    - simpleModels.qmd
    - multipleRegression.qmd
    - structuralRegression.qmd
    - moderatedRegression.qmd
    - missingdata.qmd
    - references.qmd
    - statisticalthinkinglink.qmd
  page-footer:
    left: |
      *Design and Analysis: A Computational Model-Based Approach* was written by William M. Murrah III.
    right: |
      Return to  <a href="https://www.statistical-thinking.com">statistical-thinking.com</a>.
bibliography: regmodbook.bib
csl: apa.csl
format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt



