project:
  type: book
  output-dir: docs
book:
  title: "Design and Analysis: A Computational Model-Based Approach"
  author: "William M. Murrah, III"
  chapters:
    - index.qmd
    - intro.qmd
    - simulation.qmd
    - simpleModels.qmd
    - multipleRegression.qmd
    - moderatedRegression.qmd
    - summary.qmd
    - references.qmd
    - statisticalthinkinglink.qmd
  page-footer:
    left: |
      *Design and Analysis: A Computational Model-Based Approach* was written by William M. Murrah III.
    right: |
      Return to  <a href="https://www.statistical-thinking.com">statistical-thinking.com</a>.

bibliography: regmodbook.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



